services:
  demo-java26:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: demo-java26
    ports:
      - "8080:8080"
    environment:
      APPLICATIONINSIGHTS_CONNECTION_STRING: ${APPLICATIONINSIGHTS_CONNECTION_STRING:-}
#      OTEL_SERVICE_NAME: demo-java26