services:
  demo-java26:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: demo-java26
    ports:
      - "8080:8080"
    environment:
      LOGGING_STRUCTURED_FORMAT_CONSOLE: logstash
      OTEL_SERVICE_NAME: demo-java26
#      OTEL_INSTRUMENTATION_COMMON_LOGGING_TRACE_ID_KEY: traceId
#      OTEL_INSTRUMENTATION_COMMON_LOGGING_SPAN_ID_KEY: spanId
      OTEL_INSTRUMENTATION_LOGBACK_MDC_ENABLED: "true"
      OTEL_JAVAAGENT_LOGGING: none # not spam log startup self
      OTEL_TRACES_EXPORTER: none