spring:
  application:
    name: demo-java26

server:
  port: ${PORT:8080}

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSSXXX} ${spring.application.name} [%level] - %logger - %msg%n" # only local
  level:
    root: ${LOG_LEVEL:INFO}
#    com.example.demo_java26.DemoJava26Application: ${LOG_LEVEL_MAIN:DEBUG}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

  endpoint:
    health:
      probes:
        enabled: true